const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const L=vm.runInNewContext(fs.readFileSync(root+'/source/logic.js','utf8').replace(/export /g,'')+';({setup,applyAction,viewFor,validateAction,restoreSaveFileSnapshot,ensureOperatingState,settleOperatingCosts,inventoryAge,operatingSummary,calendarPeriod,consumeStockLots,markStockArrival,addColor,invEnsure,PRODUCTS,LOCATIONS,SITE_TIERS,dateFor})');const clone=x=>JSON.parse(JSON.stringify(x));
const s=L.setup(['tester']),p=L.PRODUCTS[0];assert.equal(L.dateFor(s.day),'2027.01.15');
const old=JSON.parse(fs.readFileSync(path.join(__dirname,'v18-save-fixture.json'),'utf8')).snapshot;const migrated=L.restoreSaveFileSnapshot(old,old.players,[],0);
for(const k of ['cash','day','history','stats','productSalesProfiles','productStyleTags'])assert.deepStrictEqual(clone(migrated[k]),old[k],k);
for(const [id,i] of Object.entries(old.inventory))for(const [key,value] of Object.entries(i))assert.deepStrictEqual(clone(migrated.inventory[id][key]),value,key);
assert.deepStrictEqual(clone(L.restoreSaveFileSnapshot(migrated,migrated.players,[],0)),clone(migrated));
const i=L.invEnsure(s,p.id);i.stock=3;L.markStockArrival(s,i,1);L.addColor(i,0,3);s.day=20;i.stock+=2;L.markStockArrival(s,i,20);L.addColor(i,0,2);s.day=31;assert.equal(L.inventoryAge(s,i).longStockQty,3);assert.equal(L.inventoryAge(s,i).holdingDays,30);
L.consumeStockLots(i,0,3);i.colorStock[0]-=3;i.stock-=3;assert.equal(L.inventoryAge(s,i).longStockQty,0);assert.equal(L.inventoryAge(s,i).holdingDays,11);
L.consumeStockLots(i,0,2);i.colorStock[0]=0;i.stock=0;assert.equal(L.inventoryAge(s,i).arrivalDay,null);
s.day=40;i.stock=1;L.markStockArrival(s,i,40);L.addColor(i,0,1);assert.equal(L.inventoryAge(s,i).holdingDays,0);
const fees=L.setup(['fees']),cash=fees.cash;for(let d=1;d<=7;d++){fees.day=d;L.settleOperatingCosts(fees);if(d<7)assert.equal(fees.cash,cash)}assert.equal(cash-fees.cash,7000);const again=clone(fees);L.settleOperatingCosts(fees);assert.deepStrictEqual(clone(fees),again);
const month=L.setup(['month']);month.day=17;delete month.operatingCosts;month.store.locationId=L.LOCATIONS[0].id;month.store.size=1;month.site.tier=1;L.ensureOperatingState(month);for(let d=17;d<=46;d++){month.day=d;L.settleOperatingCosts(month)}const entry=month.operatingCosts.ledger.find(x=>x.kind==='monthly');assert.equal(entry.day,46);assert.equal(entry.rent,L.LOCATIONS[0].rent);assert.equal(entry.site,L.SITE_TIERS[1].maint);
const both=L.setup(['both']);both.day=196;both.taxReserve=300;delete both.operatingCosts;L.ensureOperatingState(both);const before=both.cash;L.settleOperatingCosts(both);assert.equal(both.operatingCosts.ledger.length,2);assert.equal(before-both.cash,1300+Math.round(L.SITE_TIERS[0].maint/30));assert.equal(both.taxReserve,0);
const stale=L.setup(['stale']);stale.day=31;const si=L.invEnsure(stale,p.id);Object.assign(si,{stock:7,colorStock:{0:7},stockLots:[{day:1,color:0,qty:7,estimated:false}]});delete stale.operatingCosts;L.ensureOperatingState(stale);const b=stale.cash;for(let d=31;d<=35;d++){stale.day=d;L.settleOperatingCosts(stale)}assert.equal(b-stale.cash,6000); // 5 days * (1000 + 7 * 200/7)
const saved=L.applyAction(migrated,migrated.players[0],{type:'saveGame',name:'V19'}),restored=L.applyAction(saved,saved.players[0],{type:'loadGame',saveId:saved.manualSaves.at(-1).id});assert.deepStrictEqual(clone(restored.operatingCosts),clone(saved.operatingCosts));
const playing=L.setup(['play']);playing.cash=10000000;const inv=L.invEnsure(playing,p.id);Object.assign(inv,{stock:50,colorStock:{0:25,1:25},shoot:1});L.ensureOperatingState(playing);let next=playing;for(let d=0;d<40;d++){next=L.applyAction(next,'play',{type:'endDay'});for(const it of Object.values(next.inventory)){assert.equal(it.stockLots.reduce((n,x)=>n+x.qty,0),it.stock);for(const [c,q] of Object.entries(it.colorStock))assert.equal(it.stockLots.filter(x=>x.color===Number(c)).reduce((n,x)=>n+x.qty,0),q)}}assert.equal(next.day,41);
console.log('PASS V18 save/migration, FIFO/reorder aging, stockout reset, weekly/monthly/combined boundary, partial/no retro billing, no duplicate billing, slot roundtrip, 40-day actual sales/color/return conservation');
