const fs=require('fs'),vm=require('vm'),assert=require('assert'),root=require('path').resolve(__dirname,'..');
function load(file,more=''){return vm.runInNewContext(fs.readFileSync(file,'utf8').replace(/export /g,'')+`;({setup,applyAction,validateAction,viewFor,updateAudience,PRODUCTS,invEnsure,restoreSaveFileSnapshot${more}})`)}
const L=load(root+'/source/logic.js',',managementStats,purchaseGenderCounts,photoGenderTarget,ensureManagementState,supplierSortData'),oldL=load(root+'/tests/v19-baseline-logic.js'),clone=x=>JSON.parse(JSON.stringify(x));
const base=oldL.setup(['test']);base.day=20;base.cash=5000000;for(let n=0;n<8;n++){const p=L.PRODUCTS[n],i=oldL.invEnsure(base,p.id);Object.assign(i,{stock:20,colorStock:{0:20},shoot:1,model:n%2?'male':'female'});}
const migrated=L.restoreSaveFileSnapshot(base,base.players,[],0);for(const k of ['cash','day','history','stats','productSalesProfiles','productStyleTags','operatingCosts'])assert.deepStrictEqual(clone(migrated[k]),clone(oldL.restoreSaveFileSnapshot(base,base.players,[],0)[k]),k);
const results=[];for(const [name,femaleCount,shotCount] of [['female',8,8],['male',0,8],['balanced',4,8],['unshot',0,0],['oneMale',0,1]]){
 const s=clone(migrated),before=clone(base);Object.values(s.inventory).forEach((i,n)=>{i.model=n<femaleCount?'female':'male';i.shoot=n<shotCount?1:0});before.inventory=clone(s.inventory);
 for(let n=0;n<15;n++){L.updateAudience(s,[]);oldL.updateAudience(before,[])}
 let female=0,male=0;for(let n=0;n<1000;n++){const counts=L.purchaseGenderCounts(s,L.PRODUCTS[n%8],10,9123+n*7919);female+=counts.female;male+=counts.male;}
 results.push({scenario:name,samples:female+male,beforeFemale:before.audience.gender.female,afterFemale:s.audience.gender.female,actualFemale:female,actualMale:male});
 const reload=L.restoreSaveFileSnapshot(s,s.players,[],0);assert.equal(L.photoGenderTarget(reload),L.photoGenderTarget(s));assert.deepStrictEqual(clone(reload.inventory),clone(s.inventory));
}
assert(results[1].actualMale>6500);assert(results[0].actualFemale>7000);assert(results[2].actualFemale>4500&&results[2].actualFemale<6000);assert(results[3].afterFemale===70);assert(results[4].actualMale<results[1].actualMale);
const s=L.setup(['stats']),p=L.PRODUCTS[0];s.day=3;s.management.sinceDay=1;s.history.sales=[{day:3,id:p.id,qty:10,revenue:1000,cogs:400,customerGender:{female:6,male:4}}];s.management.days={3:{expense:50,tax:10,refunds:100,returnedCost:40,closed:true,openStock:20,closeStock:10}};
const stats=L.managementStats(s);assert.equal(stats.periods.today.profit,480);assert.equal(stats.periods.today.margin,60);assert.equal(stats.periods.today.turnover,10/15);assert.equal(stats.bestSellerIds.length,0);s.day=10;assert.equal(L.managementStats(s).bestSellerIds.length,1);s.day=11;assert.equal(L.managementStats(s).bestSellerIds.length,0);
const play=L.setup(['play']);play.cash=5000000;const action={type:'buySample',id:L.viewFor(play,'play').catalog[0].id,color:0};assert(L.validateAction(play,'play',action).ok);let n=L.applyAction(play,'play',action);const id=action.id;assert.equal(n.management.days[1].expense,0);const shoot={type:'shoot',id,method:'horizon',model:'male',color:0};assert(L.validateAction(n,'play',shoot).ok);n=L.applyAction(n,'play',shoot);assert.equal(n.management.days[1].expense,18000);assert.equal(n.inventory[id].model,'male');n=L.applyAction(n,'play',{type:'endDay'});assert.equal(n.day,2);assert(n.management.days[1].closed);assert(n.supplierFirstTrades[L.PRODUCTS.find(p=>p.id===id)?.supplierId]);
fs.writeFileSync(root+'/tests/gender-results.json',JSON.stringify(results,null,2));fs.writeFileSync(root+'/tests/ui-fixture.json',JSON.stringify({format:'ADDER_BOUTIQUE_SAVE',schema:1,snapshot:(()=>{const x=clone(migrated);x.history.sales=Object.keys(x.inventory).slice(0,3).map((id,j)=>({id,day:19,date:'2027.02.03',qty:8-j,revenue:100000*(8-j),cogs:50000*(8-j)}));for(const row of x.history.sales){x.inventory[row.id].sold=row.qty;x.sampled[row.id]=true;}x.orderLedger=Object.keys(x.inventory).slice(0,3).map((id,j)=>({recordId:'order-'+(j+1),productId:id,supplierId:L.PRODUCTS.find(p=>p.id===id).supplierId,qty:2,color:0,orderDay:19,dueDay:21,channel:'reorder',fulfillment:'next_day',status:'pending'}));x.favoriteSuppliers=[L.PRODUCTS[0].supplierId];return x})()}));
console.log('PASS migration, 5 photo conditions x 10,000 buyers, save roundtrip, profit/margin/turnover, bestseller aging, purchase/shoot/close/first-trade');console.log(results);
